# Generated by Django 4.2.9 on 2024-01-11 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='django',
            name='pic',
            field=models.FileField(default='profile.png', upload_to='media/upload'),
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=12)),
                ('lname', models.CharField(max_length=12)),
                ('contact', models.CharField(max_length=10)),
                ('houseno', models.CharField(max_length=4)),
                ('blockno', models.CharField(max_length=2)),
                ('occupation', models.CharField(max_length=20)),
                ('job_address', models.TextField()),
                ('bloodgroup', models.CharField(max_length=15)),
                ('vehicle_details', models.CharField(max_length=5)),
                ('pic', models.FileField(default='profile.png', upload_to='media/upload')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.framework')),
            ],
        ),
    ]
